[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(\.git|__pycache__|\.venv|ml_models)
'''

[tool.flake8]
max-line-length = 120
exclude = [".git", "__pycache__", "ml_models"]
ignore = "E203, W503"
